# Using a simple nginx server to serve static json files
FROM nginx:alpine

# Copy the mock data and nginx configuration
COPY mocks/nginx.conf /etc/nginx/conf.d/default.conf
COPY mocks/data /usr/share/nginx/html/data

# Expose port 80
EXPOSE 80 